# -*- coding: utf-8 -*-
"""GOST_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136hV0rKgSA_OpSnIeuUSLx3hVIi1qUyN
"""

from google.colab import drive
drive.mount('/content/drive')

import sys


# Get the absolute path of the current folder
abspath = '/content/drive/MyDrive/Colab Notebooks/DATS 6501'

# Get the absolute path of the shallow utilities folder
data = '/content/drive/MyDrive/Colab Notebooks/DATS 6501'

import pandas as pd
import matplotlib.pyplot as plt

data  = pd.read_csv(abspath + "/data/pak1k_gpo2_urban_adm1_intersect.csv")

data.head()
data.tail()

#number of rows
len(data)

data['Pop'].sum()

data.groupby(['ADM1_EN']).sum()

data.groupby(['ADM1_EN']).count()

data['Shape_Area'].sum()

data['Pop'].min()

data.Pop.max()

data.Pop.mean()

data.Pop.median()

data.Pop.std()

data['Pop'].hist()